### ISSUE TITLE
Criar diagrama de modelagem das entidades

### ISSUE THREAD

**Issue by Fernandogr10** [the-collab-space/cinema-flix#1]
A partir de um diagrama, criar a modelagem das entidades especificando as propriedades que as mesmas deverão conter:

- [x] Definição das entidades
- [x] Definição das propriedades
- [x] Definição de relacionamentos

**Comment by DouglasLeo** [comment]
Foi feita a criação da modelagem das entidades do projeto. 

[MovieFlixDiagram.zip](https://github.com/the-collab-space/cinema-flix/files/6119846/MovieFlixDiagram.zip)
